# Site settings
title: Sayogo Wibowo
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sayogowibowo.github.io/" # the base hostname & protocol for your site

# User setting
owner: Sayogo Wibowo
email: sayogowibowo@gmail.com
facebook_username: sayogowibowo
twitter_username: SayogoWibowo
instagram_username: sayogowibowo
behance_username: sayogowibowo
github_username: sayogowibowo
pinterest_username: sayogowibowo
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Sayogo Wibowo

# API settings
google_api_key:

# Build settings
markdown: kramdown
